### ISSUE TITLE
Empty file as src/MyApplication-app.xml is not re-generated (silently)

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#26]
After an error in `generate app-descriptor`, I ended up with an empty app descriptor.

Subsequent calls to `apm generate app-descriptor` where failing silently (keeping the empty file as-is), took me a few iteration to realize I did indeed fix my issue, but had to delete the app descriptor xml file for `apm` to create a new one.

Steps to reproduce:

```
$ mkdir xxx
$ cd xxx
$ apm init
Creating new project definition file
Application Identifier [com.my.app]:
Application Name [My Application]:
Application Version [1.0.0]:
$ mkdir src
$ touch src/MyApplication-app.xml
$ apm generate app-descriptor
```

`MyApplication-app.xml` is still empty.

**Comment by marchbold** [comment]
Definitely a bug there, but this is still one area I was a little uncertain on how we should approach it. 

I was hoping for input from user's as to what they expected the output of this command to be. I was originally thinking of using a project template that the user edited but then I switched to using the output as this template.

**Comment by j3k0** [comment]
> I was hoping for input from user's as to what they expected the output of this command to be. I was originally thinking of using a project template that the user edited but then I switched to using the output as this template.

Sorry I'm probably missing something. What else could "the ouput of `generate app-descriptor`" be, except the app descriptor XML file?

In case of an error generating the xml file, it should be displayed on the console (and the XML file should probably be deleted).

**Comment by marchbold** [comment]
I meant the what inputs would be used to generate the output, ie what the user would expect the output to contain.

 This is a real first pass at this process currently and yes should definitely display an error when an empty file is used as the template.

**Comment by marchbold** [comment]
Also deleting the XML is one of my concerns for using the destination as the template as it may lose a developers app config...

**Comment by j3k0** [comment]
Where I am now, I'm wondering how to add things I already have in my app descriptor to the one generated by `apm`. Keeping the existing app descriptor as a template that would only be expended by apm might make things easier.

I don't think `apm` should edit `src/MyApplication-app.xml` in place, as it might make things complicated (to figure out what was added by human, what was added by `apm`).

This flow might be nice: `src/MyApplication-app.xml.in` > `apm` > `src/MyApplication-app.xml`.

This was `src/MyApplication-app.xml.in` can be added to the `git`, while `src/MyApplication-app.xml` is a generated file (so not added to the repo).

**Comment by j3k0** [comment]
BTW, if `src/MyApplication-app.xml.in` can also contain the manifest and plist additions, there's no need for `config/ios` and `config/android`, things differ less to a "standard" AIR project.

**Comment by j3k0** [comment]
... I get my confusion now, I just realized that the destination `xml` is also a source template!

**Comment by marchbold** [comment]
Currently it uses the destination xml as the template and modifies the sections identified in the docs https://github.com/airsdk/apm/wiki/Usage-Generate#application-descriptor

- namespace (to correctly set the AIR version)
- `id`
- `versionNumber`
- `versionLabel` (if specified)
- `android` / `manifestAdditions`
- `iPhone` / `InfoAdditions`
- `iPhone` / `Entitlements`
- `extensions`

I didn't want to use the android manifest and info additions from the destination app descriptor due to a few small concerns. Mainly around upgrading packages. Differentiating between something that is user added, versus a legacy package addition would inevitably create issues. 

This is the reason for creating a separate "config" source for these, and I had originally placed a source app descriptor in there too, just like the `MyApplication-app.app.in` you are proposing just alongside the other app descriptor configs, I think it was `config/application-descriptor.xml` 

However in testing I found it easier to use everything in the destination xml as the template. This is generally what we use to develop so make changes to it which may not get ported over to a template/config. 

But yeah, really looking for ideas here, or a configuration process, perhaps an order of precedence? If one is supplied, use that, otherwise try xx, then default to xx ... Or should we put all the potential values in the project.apm file and create a completely new xml each time ?

**Comment by marchbold** [comment]
This should be resolved in today's update

**Comment by marchbold** [comment]
I've also changed the order of precedence, it should now be:

> - `config/application-descriptor.xml`;
> - output path (either the command line parameter or the default `src/${filename}-app.xml`);
> - built-in template (if neither of the above are present);
