### ISSUE TITLE
dx tool failed:no main manifest attribute

### ISSUE THREAD

**Issue by j3k0** [airsdk/apm#66]
**NOTE: the error went away after I made the below change and regenerated the application manifest**
```
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="30" />
```
(used to be minSdkVersion="21")

---

I get this error when packaging an APK.

```
dx tool failed:no main manifest attribute, in /Users/jeko/Library/Android/sdk/build-tools/30.0.3/lib/d8.jar
```

Note that packaging an AAB works.

My guess is that "no main manifest attribute" means there's something wrong with the generated `AndroidManifest.xml`. I'm investigating.

--

logs (`-arch armv8`):
```
bin/AIRSDK_33.1.1.633/bin/adt -licenseFile adt.lic -package -target apk-debug -arch armv8 -storetype pkcs12 -keystore /path/platforms/mobile/android/fovea-devel.p12 -storepass password bin/android-debug/MyApp.apk bin/android-debug/MyApp-app.xml -C bin/android-debug MyApp.swf icons google-services.json -extdir bin/apm-mobile/libs -extdir bin/apm-mobile/ane -platformsdk /Users/jeko/Library/Android/sdk

dx tool failed:no main manifest attribute, in /Users/jeko/Library/Android/sdk/build-tools/30.0.3/lib/d8.jar
```

specifying `-arch armv7` the error is different:
```
dx tool failed:Error: D8 does not support main-dex inputs and outputs when compiling to API level 21 and above
```

**Comment by marchbold** [comment]
This looks like this issue in AIR:

https://github.com/airsdk/Adobe-Runtime-Support/issues/1149

Don't see how this is related to APM? If it is the minimum version, then you can set that in the config/android/AndroidManifest.xml file. 

I'll check with Andrew if there are plans to ditch earlier Android versions.

**Comment by ajwfrost** [comment]
@j3k0 the initial error there - `no main manifest attribute` - is because the version of d8.jar in the Android build tools has changed so it no longer includes the main class name in the JAR manifest, which means you can no longer just run it as an executable jar file. We've got a workaround for this within the 33.1.1.633 build of the AIR SDK that was released yesterday.

For the later error regarding main-dex inputs, we've not seen that before so will check, but it also looks like it's related to this new version of d8.jar (from build tools 30.0.3 and above: if you don't provide an Android SDK path then we use an older version of d8.jar that ships with the AIR SDK instead...)

thanks

**Comment by j3k0** [comment]
Thanks for looking this up. I'm using android build tools `30.0.2`. After mangling around, the build started working (using AIR SDK `33.1.1.633`)

I'll let you know if I see this error again, eventually learn more about it.
